/**
 * 高等数学期末复习示例数据
 * 一键加载 1 个资料、8 个知识点、41 道题目，覆盖极限、导数、积分、
 * 微分方程、级数、多元函数、线性代数、概率论。
 *
 * 类型定义对应 src/store/useAppStore.ts 中的
 * StudyMaterial / KnowledgePoint / Question（此处使用内联类型，不导入 store，避免循环依赖）。
 *
 * 注意：所有 LaTeX 公式中的反斜杠在字符串字面量中需双写，
 * 例如 '$\\frac{1}{x}$' 渲染为 $\frac{1}{x}$。
 */

export interface StudyMaterial {
  id: string;
  name: string;
  type: 'pdf' | 'word' | 'ppt' | 'text' | 'markdown';
  kind: 'knowledge' | 'bank' | 'auto';
  size: number;
  uploadedAt: number;
  parsedText?: string;
  status: 'pending' | 'parsing' | 'parsed' | 'failed';
}

export interface KnowledgePoint {
  id: string;
  materialId: string;
  name: string;
  description: string;
  priority: number; // 1-5
  mastery: number; // 0-1
  relatedIds: string[];
  tags: string[];
  createdAt: number;
}

export interface Question {
  id: string;
  materialId: string;
  knowledgePointIds: string[];
  type: 'choice' | 'fill' | 'short' | 'calculation';
  difficulty: 1 | 2 | 3 | 4 | 5;
  stem: string;
  options?: string[];
  answer: string;
  explanation: string;
  source: 'bank' | 'ai';
  bankId?: string;
  aiFilled?: boolean;
  createdAt: number;
}

export interface DemoData {
  materials: StudyMaterial[];
  knowledgePoints: KnowledgePoint[];
  questions: Question[];
}

export function buildDemoData(): DemoData {
  const now = Date.now();
  const materialId = 'demo-mat-1';
  // 掌握度随机分布在 0.3 ~ 0.7
  const randMastery = () => 0.3 + Math.random() * 0.4;

  const materials: StudyMaterial[] = [
    {
      id: materialId,
      name: '高等数学期末复习要点',
      type: 'text',
      kind: 'bank',
      size: 120000,
      uploadedAt: now,
      status: 'parsed',
    },
  ];

  const knowledgePoints: KnowledgePoint[] = [
    {
      id: 'kp-limit',
      materialId,
      name: '极限',
      description: '数列极限、函数极限、两个重要极限、等价无穷小与夹逼准则。',
      priority: 5,
      mastery: randMastery(),
      relatedIds: ['kp-derivative', 'kp-series'],
      tags: ['高等数学', '极限'],
      createdAt: now,
    },
    {
      id: 'kp-derivative',
      materialId,
      name: '导数',
      description: '导数定义、求导法则、复合函数与隐函数求导、参数方程与高阶导数。',
      priority: 5,
      mastery: randMastery(),
      relatedIds: ['kp-limit', 'kp-integral'],
      tags: ['高等数学', '导数'],
      createdAt: now,
    },
    {
      id: 'kp-integral',
      materialId,
      name: '积分',
      description: '不定积分、定积分、换元法、分部积分法与广义积分。',
      priority: 5,
      mastery: randMastery(),
      relatedIds: ['kp-derivative', 'kp-diffeq'],
      tags: ['高等数学', '积分'],
      createdAt: now,
    },
    {
      id: 'kp-diffeq',
      materialId,
      name: '微分方程',
      description: '可分离变量、一阶线性、二阶常系数齐次与非齐次微分方程。',
      priority: 4,
      mastery: randMastery(),
      relatedIds: ['kp-integral', 'kp-derivative'],
      tags: ['高等数学', '微分方程'],
      createdAt: now,
    },
    {
      id: 'kp-series',
      materialId,
      name: '级数',
      description: '常数项级数敛散性判别、幂级数收敛半径、泰勒级数展开。',
      priority: 4,
      mastery: randMastery(),
      relatedIds: ['kp-limit'],
      tags: ['高等数学', '级数'],
      createdAt: now,
    },
    {
      id: 'kp-multivar',
      materialId,
      name: '多元函数',
      description: '偏导数、全微分、多元复合函数求导、二重积分与拉格朗日乘数法。',
      priority: 4,
      mastery: randMastery(),
      relatedIds: ['kp-derivative', 'kp-integral'],
      tags: ['高等数学', '多元函数'],
      createdAt: now,
    },
    {
      id: 'kp-linalg',
      materialId,
      name: '线性代数',
      description: '行列式、矩阵运算、逆矩阵、特征值与特征向量。',
      priority: 3,
      mastery: randMastery(),
      relatedIds: ['kp-multivar'],
      tags: ['高等数学', '线性代数'],
      createdAt: now,
    },
    {
      id: 'kp-prob',
      materialId,
      name: '概率论',
      description: '古典概率、条件概率、随机变量的期望与正态分布。',
      priority: 3,
      mastery: randMastery(),
      relatedIds: ['kp-linalg'],
      tags: ['高等数学', '概率论'],
      createdAt: now,
    },
  ];

  const questions: Question[] = [
    // ───────────── 极限 kp-limit ─────────────
    {
      id: 'q1',
      materialId,
      knowledgePointIds: ['kp-limit'],
      type: 'choice',
      difficulty: 1,
      stem: '求极限 $\\lim_{x \\to 0} \\frac{\\sin x}{x}$ 的值为（）',
      options: ['A. $0$', 'B. $1$', 'C. $\\infty$', 'D. 不存在'],
      answer: 'B',
      explanation: '这是重要极限，$\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1$，可由夹逼准则证明。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q2',
      materialId,
      knowledgePointIds: ['kp-limit'],
      type: 'choice',
      difficulty: 2,
      stem: '求极限 $\\lim_{n \\to \\infty} \\left(1 + \\frac{1}{n}\\right)^n$ 的值为（）',
      options: ['A. $1$', 'B. $e$', 'C. $0$', 'D. $\\infty$'],
      answer: 'B',
      explanation: '这是重要极限之一，$\\lim_{n \\to \\infty}\\left(1+\\frac{1}{n}\\right)^n = e$，其中 $e \\approx 2.71828$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q3',
      materialId,
      knowledgePointIds: ['kp-limit'],
      type: 'fill',
      difficulty: 1,
      stem: '求极限 $\\lim_{x \\to 0} \\frac{e^x - 1}{x} = \\underline{\\quad\\quad}$。',
      answer: '$1$',
      explanation: '当 $x \\to 0$ 时 $e^x - 1 \\sim x$，故 $\\lim_{x \\to 0} \\frac{e^x - 1}{x} = 1$。也可用洛必达法则：$\\lim_{x \\to 0} \\frac{e^x}{1} = 1$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q4',
      materialId,
      knowledgePointIds: ['kp-limit'],
      type: 'short',
      difficulty: 4,
      stem: '用夹逼准则证明 $\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1$。',
      answer: '由 $\\cos x \\le \\frac{\\sin x}{x} \\le 1$（$x \\in (0,\\frac{\\pi}{2})$）且 $\\lim_{x \\to 0}\\cos x = 1$，由夹逼准则得 $\\lim_{x \\to 0}\\frac{\\sin x}{x} = 1$。',
      explanation: '关键是在 $\\sin x \\le x \\le \\tan x$（$x \\in (0,\\frac{\\pi}{2})$）基础上同除 $\\sin x$，得 $1 \\le \\frac{x}{\\sin x} \\le \\frac{1}{\\cos x}$，取倒数即 $\\cos x \\le \\frac{\\sin x}{x} \\le 1$，两端极限均为 $1$，夹逼得证。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q5',
      materialId,
      knowledgePointIds: ['kp-limit'],
      type: 'short',
      difficulty: 5,
      stem: '求极限 $\\lim_{x \\to 0} \\frac{\\tan x - \\sin x}{x^3}$。',
      answer: '$\\frac{1}{2}$',
      explanation: '$\\tan x - \\sin x = \\frac{\\sin x}{\\cos x} - \\sin x = \\sin x \\cdot \\frac{1 - \\cos x}{\\cos x}$。当 $x \\to 0$ 时 $\\sin x \\sim x$，$1 - \\cos x \\sim \\frac{x^2}{2}$，$\\cos x \\to 1$，故原式 $= \\lim_{x \\to 0}\\frac{x \\cdot \\frac{x^2}{2}}{x^3 \\cdot 1} = \\frac{1}{2}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q6',
      materialId,
      knowledgePointIds: ['kp-limit'],
      type: 'short',
      difficulty: 4,
      stem: '设 $x \\to 0$ 时，$\\sqrt{1+x^2} - 1$ 与 $\\sin^a x$（$a>0$）为同阶无穷小，求 $a$。',
      answer: '$a = 2$',
      explanation: '$\\sqrt{1+x^2}-1 = \\frac{x^2}{\\sqrt{1+x^2}+1} \\sim \\frac{x^2}{2}$（$x \\to 0$），而 $\\sin^a x \\sim x^a$。两者同阶意味着 $a = 2$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },

    // ───────────── 导数 kp-derivative ─────────────
    {
      id: 'q7',
      materialId,
      knowledgePointIds: ['kp-derivative'],
      type: 'choice',
      difficulty: 1,
      stem: '设 $f(x) = x^2$，则 $f\'(x) = （）$',
      options: ['A. $x$', 'B. $2x$', 'C. $x^2$', 'D. $2$'],
      answer: 'B',
      explanation: '由幂函数求导公式 $(x^n)\' = n x^{n-1}$，得 $(x^2)\' = 2x$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q8',
      materialId,
      knowledgePointIds: ['kp-derivative'],
      type: 'choice',
      difficulty: 2,
      stem: '设 $y = \\sin(2x)$，则 $\\frac{dy}{dx} = （）$',
      options: ['A. $\\cos(2x)$', 'B. $2\\cos(2x)$', 'C. $-\\cos(2x)$', 'D. $-2\\cos(2x)$'],
      answer: 'B',
      explanation: '复合函数求导：$\\frac{d}{dx}\\sin(2x) = \\cos(2x) \\cdot (2x)\' = 2\\cos(2x)$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q9',
      materialId,
      knowledgePointIds: ['kp-derivative'],
      type: 'fill',
      difficulty: 1,
      stem: '设 $f(x) = \\ln x$，则 $f\'(e) = \\underline{\\quad\\quad}$。',
      answer: '$\\frac{1}{e}$',
      explanation: '$(\\ln x)\' = \\frac{1}{x}$，代入 $x = e$ 得 $f\'(e) = \\frac{1}{e}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q10',
      materialId,
      knowledgePointIds: ['kp-derivative'],
      type: 'short',
      difficulty: 4,
      stem: '设 $y$ 由方程 $e^y + x y - e = 0$ 确定，求 $\\frac{dy}{dx}$。',
      answer: '$\\frac{dy}{dx} = -\\frac{y}{e^y + x}$',
      explanation: '对方程两边关于 $x$ 求导：$e^y \\cdot y\' + y + x y\' = 0$，整理得 $(e^y + x) y\' = -y$，故 $y\' = -\\frac{y}{e^y + x}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q11',
      materialId,
      knowledgePointIds: ['kp-derivative'],
      type: 'short',
      difficulty: 5,
      stem: '设 $\\begin{cases} x = t - \\sin t \\\\ y = 1 - \\cos t \\end{cases}$，求 $\\frac{d^2 y}{dx^2}$。',
      answer: '$\\frac{d^2 y}{dx^2} = -\\frac{1}{(1-\\cos t)^2}$',
      explanation: '$\\frac{dy}{dx} = \\frac{\\dot y}{\\dot x} = \\frac{\\sin t}{1 - \\cos t}$。再求二阶导 $\\frac{d^2y}{dx^2} = \\frac{d}{dt}\\left(\\frac{\\sin t}{1-\\cos t}\\right) \\big/ \\frac{dx}{dt}$，其中 $\\frac{d}{dt}\\left(\\frac{\\sin t}{1-\\cos t}\\right) = \\frac{-1}{1-\\cos t}$，故 $\\frac{d^2y}{dx^2} = -\\frac{1}{(1-\\cos t)^2}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q12',
      materialId,
      knowledgePointIds: ['kp-derivative'],
      type: 'short',
      difficulty: 4,
      stem: '设 $y = \\sin x$，求 $y^{(n)}$。',
      answer: '$y^{(n)} = \\sin\\left(x + \\frac{n\\pi}{2}\\right)$',
      explanation: '$y\' = \\cos x = \\sin(x+\\frac{\\pi}{2})$，$y\'\' = -\\sin x = \\sin(x+\\pi)$，由数学归纳法得 $y^{(n)} = \\sin\\left(x + \\frac{n\\pi}{2}\\right)$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },

    // ───────────── 积分 kp-integral ─────────────
    {
      id: 'q13',
      materialId,
      knowledgePointIds: ['kp-integral'],
      type: 'choice',
      difficulty: 1,
      stem: '$\\int x \\, dx = （）$',
      options: ['A. $x + C$', 'B. $\\frac{x^2}{2} + C$', 'C. $\\frac{x^2}{2}$', 'D. $x$'],
      answer: 'B',
      explanation: '由幂函数积分公式 $\\int x^n \\, dx = \\frac{x^{n+1}}{n+1} + C$（$n \\neq -1$），得 $\\int x \\, dx = \\frac{x^2}{2} + C$。注意不定积分必须带常数 $C$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q14',
      materialId,
      knowledgePointIds: ['kp-integral'],
      type: 'choice',
      difficulty: 2,
      stem: '$\\int \\sin x \\, dx = （）$',
      options: ['A. $\\cos x + C$', 'B. $-\\cos x + C$', 'C. $\\cos x$', 'D. $\\sin x + C$'],
      answer: 'B',
      explanation: '由于 $(-\\cos x)\' = \\sin x$，所以 $\\int \\sin x \\, dx = -\\cos x + C$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q15',
      materialId,
      knowledgePointIds: ['kp-integral'],
      type: 'fill',
      difficulty: 3,
      stem: '计算定积分 $\\int_0^1 x^2 \\, dx = \\underline{\\quad\\quad}$。',
      answer: '$\\frac{1}{3}$',
      explanation: '由牛顿-莱布尼茨公式：$\\int_0^1 x^2 \\, dx = \\left[\\frac{x^3}{3}\\right]_0^1 = \\frac{1}{3} - 0 = \\frac{1}{3}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q16',
      materialId,
      knowledgePointIds: ['kp-integral'],
      type: 'short',
      difficulty: 3,
      stem: '计算不定积分 $\\int x e^x \\, dx$。',
      answer: '$x e^x - e^x + C$',
      explanation: '用分部积分法，令 $u = x$，$dv = e^x \\, dx$，则 $du = dx$，$v = e^x$。于是 $\\int x e^x \\, dx = x e^x - \\int e^x \\, dx = x e^x - e^x + C$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q17',
      materialId,
      knowledgePointIds: ['kp-integral'],
      type: 'short',
      difficulty: 5,
      stem: '计算定积分 $\\int_0^4 \\frac{1}{1 + \\sqrt{x}} \\, dx$。',
      answer: '$4 - 2\\ln 3$',
      explanation: '令 $t = \\sqrt{x}$，则 $x = t^2$，$dx = 2t \\, dt$。当 $x = 0$ 时 $t = 0$，$x = 4$ 时 $t = 2$。原式 $= \\int_0^2 \\frac{2t}{1+t} \\, dt = 2\\int_0^2\\left(1 - \\frac{1}{1+t}\\right) dt = 2\\left[t - \\ln(1+t)\\right]_0^2 = 2(2 - \\ln 3) = 4 - 2\\ln 3$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q18',
      materialId,
      knowledgePointIds: ['kp-integral'],
      type: 'short',
      difficulty: 4,
      stem: '判断广义积分 $\\int_1^{+\\infty} \\frac{1}{x^2} \\, dx$ 的敛散性，若收敛求其值。',
      answer: '收敛，值为 $1$',
      explanation: '$\\int_1^{+\\infty} \\frac{1}{x^2} \\, dx = \\lim_{b \\to +\\infty}\\left[-\\frac{1}{x}\\right]_1^b = \\lim_{b \\to +\\infty}\\left(1 - \\frac{1}{b}\\right) = 1$，故该广义积分收敛，值为 $1$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },

    // ───────────── 微分方程 kp-diffeq ─────────────
    {
      id: 'q19',
      materialId,
      knowledgePointIds: ['kp-diffeq'],
      type: 'choice',
      difficulty: 1,
      stem: '微分方程 $\\frac{dy}{dx} = 2x$ 的通解为（）',
      options: ['A. $y = x^2 + C$', 'B. $y = 2x^2 + C$', 'C. $y = 2x + C$', 'D. $y = x^2$'],
      answer: 'A',
      explanation: '两边积分：$y = \\int 2x \\, dx = x^2 + C$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q20',
      materialId,
      knowledgePointIds: ['kp-diffeq'],
      type: 'choice',
      difficulty: 3,
      stem: '微分方程 $\\frac{dy}{dx} + y = 0$ 的通解为（）',
      options: ['A. $y = C e^x$', 'B. $y = C e^{-x}$', 'C. $y = C x$', 'D. $y = C$'],
      answer: 'B',
      explanation: '可分离变量：$\\frac{dy}{y} = -dx$，积分得 $\\ln|y| = -x + C_1$，故 $y = C e^{-x}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q21',
      materialId,
      knowledgePointIds: ['kp-diffeq'],
      type: 'fill',
      difficulty: 2,
      stem: '微分方程 $\\frac{dy}{dx} = x$ 满足 $y(0) = 1$ 的特解为 $y = \\underline{\\quad\\quad}$。',
      answer: '$\\frac{x^2}{2} + 1$',
      explanation: '通解 $y = \\frac{x^2}{2} + C$，代入 $y(0) = 1$ 得 $C = 1$，故特解 $y = \\frac{x^2}{2} + 1$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q22',
      materialId,
      knowledgePointIds: ['kp-diffeq'],
      type: 'short',
      difficulty: 4,
      stem: '求微分方程 $y\'\' + y = 0$ 的通解。',
      answer: '$y = C_1 \\cos x + C_2 \\sin x$',
      explanation: '特征方程 $r^2 + 1 = 0$，特征根 $r = \\pm i$。故通解为 $y = C_1 \\cos x + C_2 \\sin x$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q23',
      materialId,
      knowledgePointIds: ['kp-diffeq'],
      type: 'short',
      difficulty: 5,
      stem: '求微分方程 $y\'\' - 3y\' + 2y = e^{2x}$ 的通解。',
      answer: '$y = C_1 e^x + C_2 e^{2x} + x e^{2x}$',
      explanation: '齐次特征方程 $r^2 - 3r + 2 = 0$，根 $r_1 = 1, r_2 = 2$，齐次通解 $Y = C_1 e^x + C_2 e^{2x}$。由于 $e^{2x}$ 中 $2$ 是单特征根，设特解 $y^* = Ax e^{2x}$，代入方程解得 $A = 1$。故通解 $y = C_1 e^x + C_2 e^{2x} + x e^{2x}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },

    // ───────────── 级数 kp-series ─────────────
    {
      id: 'q24',
      materialId,
      knowledgePointIds: ['kp-series'],
      type: 'choice',
      difficulty: 2,
      stem: '等比级数 $\\sum_{n=0}^{\\infty} \\frac{1}{2^n}$ 的和为（）',
      options: ['A. $1$', 'B. $2$', 'C. $\\infty$', 'D. $\\frac{1}{2}$'],
      answer: 'B',
      explanation: '公比 $r = \\frac{1}{2}$，$|r| < 1$ 收敛，和 $S = \\frac{a_0}{1-r} = \\frac{1}{1 - \\frac{1}{2}} = 2$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q25',
      materialId,
      knowledgePointIds: ['kp-series'],
      type: 'choice',
      difficulty: 3,
      stem: '下列级数中收敛的是（）',
      options: [
        'A. $\\sum_{n=1}^{\\infty} \\frac{1}{n}$',
        'B. $\\sum_{n=1}^{\\infty} \\frac{1}{\\sqrt{n}}$',
        'C. $\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$',
        'D. $\\sum_{n=1}^{\\infty} \\frac{1}{\\ln n}$',
      ],
      answer: 'C',
      explanation: '$p$ 级数 $\\sum \\frac{1}{n^p}$ 当 $p > 1$ 时收敛。A（$p=1$，调和级数）、B（$p=\\frac{1}{2}$）、D 均发散；C 中 $p = 2 > 1$，收敛。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q26',
      materialId,
      knowledgePointIds: ['kp-series'],
      type: 'fill',
      difficulty: 3,
      stem: '幂级数 $\\sum_{n=1}^{\\infty} \\frac{x^n}{n}$ 的收敛半径 $R = \\underline{\\quad\\quad}$。',
      answer: '$1$',
      explanation: '由 $a_n = \\frac{1}{n}$，$R = \\lim_{n \\to \\infty}\\left|\\frac{a_n}{a_{n+1}}\\right| = \\lim_{n \\to \\infty}\\frac{n+1}{n} = 1$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q27',
      materialId,
      knowledgePointIds: ['kp-series'],
      type: 'short',
      difficulty: 4,
      stem: '将函数 $f(x) = e^x$ 在 $x = 0$ 处展开为麦克劳林级数。',
      answer: '$e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!} = 1 + x + \\frac{x^2}{2!} + \\frac{x^3}{3!} + \\cdots$，$x \\in (-\\infty, +\\infty)$',
      explanation: '由 $f^{(n)}(0) = 1$，得麦克劳林级数 $e^x = \\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$。其收敛半径 $R = +\\infty$，对一切 $x \\in \\mathbb{R}$ 成立。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q28',
      materialId,
      knowledgePointIds: ['kp-series'],
      type: 'short',
      difficulty: 5,
      stem: '判断级数 $\\sum_{n=1}^{\\infty} (-1)^{n+1} \\frac{1}{n}$ 的敛散性（绝对收敛、条件收敛或发散）。',
      answer: '条件收敛',
      explanation: '该级数为交错级数，$\\frac{1}{n}$ 单调递减趋于 $0$，由莱布尼茨判别法知其收敛。但 $\\sum_{n=1}^{\\infty}\\left|(-1)^{n+1}\\frac{1}{n}\\right| = \\sum\\frac{1}{n}$ 为发散的调和级数，故原级数条件收敛。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },

    // ───────────── 多元函数 kp-multivar ─────────────
    {
      id: 'q29',
      materialId,
      knowledgePointIds: ['kp-multivar'],
      type: 'choice',
      difficulty: 2,
      stem: '设 $f(x, y) = x^2 y$，则 $\\frac{\\partial f}{\\partial x} = （）$',
      options: ['A. $2xy$', 'B. $x^2$', 'C. $y$', 'D. $2x$'],
      answer: 'A',
      explanation: '对 $x$ 求偏导时把 $y$ 视为常数，故 $\\frac{\\partial f}{\\partial x} = 2xy$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q30',
      materialId,
      knowledgePointIds: ['kp-multivar'],
      type: 'choice',
      difficulty: 3,
      stem: '函数 $z = x^2 + y^2$ 在点 $(1, 1)$ 处的全微分 $dz = （）$',
      options: ['A. $2dx + 2dy$', 'B. $dx + dy$', 'C. $2x \\, dx + 2y \\, dy$', 'D. $2dx$'],
      answer: 'A',
      explanation: '$\\frac{\\partial z}{\\partial x} = 2x = 2$，$\\frac{\\partial z}{\\partial y} = 2y = 2$，故 $dz = 2\\,dx + 2\\,dy$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q31',
      materialId,
      knowledgePointIds: ['kp-multivar'],
      type: 'fill',
      difficulty: 2,
      stem: '计算二重积分 $\\iint_D 1 \\, d\\sigma$，其中 $D = \\{(x,y) \\mid 0 \\le x \\le 1,\\ 0 \\le y \\le 1\\}$，其值为 $\\underline{\\quad\\quad}$。',
      answer: '$1$',
      explanation: '该积分表示区域 $D$ 的面积。$D$ 是边长为 $1$ 的正方形，面积为 $1 \\times 1 = 1$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q32',
      materialId,
      knowledgePointIds: ['kp-multivar'],
      type: 'short',
      difficulty: 4,
      stem: '设 $z = u^2 v$，$u = x + y$，$v = x - y$，求 $\\frac{\\partial z}{\\partial x}$。',
      answer: '$\\frac{\\partial z}{\\partial x} = (x+y)(3x-y)$',
      explanation: '由链式法则 $\\frac{\\partial z}{\\partial x} = \\frac{\\partial z}{\\partial u}\\frac{\\partial u}{\\partial x} + \\frac{\\partial z}{\\partial v}\\frac{\\partial v}{\\partial x} = 2uv + u^2 = u(2v+u)$。代入 $u = x+y$，$v = x-y$ 得 $(x+y)\\bigl[2(x-y)+(x+y)\\bigr] = (x+y)(3x-y)$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q33',
      materialId,
      knowledgePointIds: ['kp-multivar'],
      type: 'short',
      difficulty: 5,
      stem: '用拉格朗日乘数法求函数 $f(x, y) = xy$ 在约束 $x + y = 1$ 下的最大值。',
      answer: '最大值为 $\\frac{1}{4}$',
      explanation: '构造拉格朗日函数 $L = xy + \\lambda(1 - x - y)$。由 $\\frac{\\partial L}{\\partial x} = y - \\lambda = 0$，$\\frac{\\partial L}{\\partial y} = x - \\lambda = 0$ 得 $x = y$。代入约束 $x + y = 1$ 得 $x = y = \\frac{1}{2}$。故最大值 $f = \\frac{1}{2} \\cdot \\frac{1}{2} = \\frac{1}{4}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },

    // ───────────── 线性代数 kp-linalg ─────────────
    {
      id: 'q34',
      materialId,
      knowledgePointIds: ['kp-linalg'],
      type: 'choice',
      difficulty: 1,
      stem: '行列式 $\\begin{vmatrix} 1 & 2 \\\\ 3 & 4 \\end{vmatrix} = （）$',
      options: ['A. $-2$', 'B. $2$', 'C. $10$', 'D. $-10$'],
      answer: 'A',
      explanation: '二阶行列式 $\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix} = ad - bc$，故 $1 \\times 4 - 2 \\times 3 = 4 - 6 = -2$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q35',
      materialId,
      knowledgePointIds: ['kp-linalg'],
      type: 'fill',
      difficulty: 3,
      stem: '设 $A = \\begin{pmatrix} 1 & 2 \\end{pmatrix}$，$B = \\begin{pmatrix} 3 \\\\ 4 \\end{pmatrix}$，则 $AB = \\underline{\\quad\\quad}$。',
      answer: '$11$',
      explanation: '$AB = 1 \\times 3 + 2 \\times 4 = 3 + 8 = 11$，结果为 $1 \\times 1$ 矩阵，即数值 $11$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q36',
      materialId,
      knowledgePointIds: ['kp-linalg'],
      type: 'short',
      difficulty: 4,
      stem: '求矩阵 $A = \\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$ 的逆矩阵。',
      answer: '$A^{-1} = \\begin{pmatrix} -2 & 1 \\\\ \\frac{3}{2} & -\\frac{1}{2} \\end{pmatrix}$',
      explanation: '$|A| = 1 \\times 4 - 2 \\times 3 = -2 \\neq 0$，可逆。二阶矩阵逆公式 $A^{-1} = \\frac{1}{|A|}\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix} = \\frac{1}{-2}\\begin{pmatrix} 4 & -2 \\\\ -3 & 1 \\end{pmatrix} = \\begin{pmatrix} -2 & 1 \\\\ \\frac{3}{2} & -\\frac{1}{2} \\end{pmatrix}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q37',
      materialId,
      knowledgePointIds: ['kp-linalg'],
      type: 'short',
      difficulty: 5,
      stem: '求矩阵 $A = \\begin{pmatrix} 2 & 1 \\\\ 1 & 2 \\end{pmatrix}$ 的特征值与特征向量。',
      answer: '特征值 $\\lambda_1 = 1$，对应特征向量 $k\\begin{pmatrix} 1 \\\\ -1 \\end{pmatrix}$（$k \\neq 0$）；特征值 $\\lambda_2 = 3$，对应特征向量 $k\\begin{pmatrix} 1 \\\\ 1 \\end{pmatrix}$（$k \\neq 0$）。',
      explanation: '特征方程 $|A - \\lambda I| = (2-\\lambda)^2 - 1 = \\lambda^2 - 4\\lambda + 3 = (\\lambda-1)(\\lambda-3) = 0$，得 $\\lambda_1 = 1,\\ \\lambda_2 = 3$。对 $\\lambda_1 = 1$，解 $(A-I)x = 0$ 得 $x_1 + x_2 = 0$，特征向量 $\\begin{pmatrix}1\\\\-1\\end{pmatrix}$；对 $\\lambda_2 = 3$，解 $(A-3I)x = 0$ 得 $-x_1 + x_2 = 0$，特征向量 $\\begin{pmatrix}1\\\\1\\end{pmatrix}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },

    // ───────────── 概率论 kp-prob ─────────────
    {
      id: 'q38',
      materialId,
      knowledgePointIds: ['kp-prob'],
      type: 'choice',
      difficulty: 1,
      stem: '掷一枚均匀骰子，出现点数为偶数的概率为（）',
      options: ['A. $\\frac{1}{6}$', 'B. $\\frac{1}{3}$', 'C. $\\frac{1}{2}$', 'D. $\\frac{2}{3}$'],
      answer: 'C',
      explanation: '骰子出现 $2$、$4$、$6$ 为偶数，共 $3$ 种情况，总样本点 $6$ 个，故概率 $\\frac{3}{6} = \\frac{1}{2}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q39',
      materialId,
      knowledgePointIds: ['kp-prob'],
      type: 'fill',
      difficulty: 2,
      stem: '设随机变量 $X$ 服从 $0\\text{-}1$ 分布，$P(X=1) = 0.6$，则 $E(X) = \\underline{\\quad\\quad}$。',
      answer: '$0.6$',
      explanation: '$0\\text{-}1$ 分布的期望 $E(X) = p = 0.6$。也可直接计算 $E(X) = 0 \\times 0.4 + 1 \\times 0.6 = 0.6$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q40',
      materialId,
      knowledgePointIds: ['kp-prob'],
      type: 'short',
      difficulty: 3,
      stem: '袋中有 $3$ 个红球、$2$ 个白球，从中不放回地依次取 $2$ 个球。求在第一次取到红球的条件下，第二次也取到红球的概率。',
      answer: '$\\frac{1}{2}$',
      explanation: '设 $A$ = 第一次取到红球，$B$ = 第二次取到红球。第一次取走红球后，袋中剩 $2$ 个红球、$2$ 个白球，共 $4$ 个球，故 $P(B \\mid A) = \\frac{2}{4} = \\frac{1}{2}$。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
    {
      id: 'q41',
      materialId,
      knowledgePointIds: ['kp-prob'],
      type: 'short',
      difficulty: 5,
      stem: '设随机变量 $X \\sim N(\\mu, \\sigma^2)$，写出其概率密度函数，并说明 $\\mu$ 与 $\\sigma$ 的几何意义。',
      answer: '$f(x) = \\frac{1}{\\sqrt{2\\pi}\\,\\sigma} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}$；$\\mu$ 为分布的对称中心（均值），$\\sigma$ 为标准差，$\\sigma$ 越小曲线越陡峭。',
      explanation: '正态分布密度函数 $f(x) = \\frac{1}{\\sqrt{2\\pi}\\,\\sigma} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}$。$\\mu$ 决定曲线中心位置（期望），$\\sigma^2$ 为方差；$\\sigma$ 越小，分布越集中、曲线越尖。由 $3\\sigma$ 法则，约 $99.7\\%$ 的取值落在 $\\mu \\pm 3\\sigma$ 内。',
      source: 'bank',
      bankId: materialId,
      createdAt: now,
    },
  ];

  return { materials, knowledgePoints, questions };
}
